In [1]:
# Import Numpy Library
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from IPython.display import Image

In [4]:
a1=np.arange(100, 10, -10)
a1

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [6]:
# Bytes consumed by one element of an array object
a1.itemsize


4

In [10]:
#Bytes Consumed by array object 
a1.nbytes

36

In [11]:
len(a1)

9

In [12]:
# Repeat 10 five times in an array
np.repeat(10,5)


array([10, 10, 10, 10, 10])

In [13]:
# Repeat each element in array 'a' thrice
a= np.array([10,20,30])
np.repeat(a,3)


array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [14]:
# Array of 10's
np.full(5,10)


array([10, 10, 10, 10, 10])

In [15]:
# Generate array of Odd numbers
ar1 = np.arange(1,20)
ar1[ar1%2 ==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
ar1=np.arange(1,20)

ar1[ar1%2==1]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [22]:
# Generate evenly spaced 4 numbers between 10 to 20.
np.linspace(100,300,4)

array([100.        , 166.66666667, 233.33333333, 300.        ])

In [23]:
# Generate evenly spaced 11 numbers between 10 to 20.
np.linspace(10,20,11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [33]:
# Generate an array of Random Integer numbers
np.random.randint(0,500,10)

array([305, 311, 451,   2, 340,  39, 322,  84,  47, 445])

In [41]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(288)
np.random.randint(0,500,10)

array([162, 329,  40, 169, 472, 419, 143, 140, 424, 191])

In [44]:
# Generate array of Random float numbers
f1 = np.random.uniform(5,10, size=(10))
f1

array([5.53021   , 6.20296778, 9.15379384, 6.33963948, 5.90208696,
       6.86770633, 9.46020781, 8.94349569, 9.42387881, 7.59024084])

In [45]:
np.floor(f1)

array([5., 6., 9., 6., 5., 6., 9., 8., 9., 7.])

In [46]:
np.trunc(f1)

array([5., 6., 9., 6., 5., 6., 9., 8., 9., 7.])

In [47]:
# Convert Float Array to Integer array
f1.astype(int)

array([5, 6, 9, 6, 5, 6, 9, 8, 9, 7])

In [89]:
arr2 = np.random.randint(1,500,10)
arr2

array([115, 339, 299, 436, 431, 135, 472,  81, 481,  56])

In [57]:
# Find Minimum number in an array
arr2.min()

22

In [58]:
# Find Maximum number in an array
arr2.max()

342

In [59]:
# Find index Minimum number in an array
arr2.argmin()

1

In [60]:
# Find Index of maximum number in an array
arr2.argmax()

7

In [61]:
# Find mean of all numbers in an array
arr2.mean()

145.3

In [68]:
#find median

np.median(arr2)


89.5

In [72]:
np.var(arr2)

13743.810000000001

In [73]:
np.std(arr2)

117.23399677567937

In [74]:
# Calculating percentiles
np.percentile(arr2,70)

165.99999999999997

In [87]:
a=np.array([10,20,30,40])

In [84]:
np.percentile(a,75)

32.5

In [91]:
# 10th & 70th percentile
np.percentile(arr2,[25,50,75])

array([120.  , 319.  , 434.75])

In [92]:
A = np.array([[1,2,3,0] , [5,6,7,22] , [10 , 11 , 1 ,13] , [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [93]:
A.max()

22

In [94]:
A.min()

0

In [95]:
A.argmin()

3

In [96]:
np.argmin(A)

3

In [98]:
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [97]:
# Column wise mimimum value
np.amin(A, axis=0)

array([1, 2, 1, 0])

In [99]:
np.amin(A,axis=1)

array([0, 5, 1, 3])

In [100]:
np.amax(A, axis=0)

array([14, 15, 16, 22])

In [101]:
np.amax(A, axis=1)

array([ 3, 22, 13, 16])

In [102]:
# Enumerate for Numpy 2D Arrays
for index, value in np.ndenumerate(A):
 print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


# Replace elements in array

In [103]:
ar = np.arange(1,20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [104]:
# Replace EVEN numbers with ZERO
rep1 = np.where(ar % 2 == 0, 0 , ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [106]:
np.where?

In [110]:
np.where(ar < 5, ar, 10*ar)

array([  1,   2,   3,   4,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190])

In [111]:
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [112]:
# Replace EVEN numbers with ZERO
rep1 = np.where(ar % 2 == 0, 0 , ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [114]:
p2 = np.arange(0,100,10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.put(p2, [0, 3 , 5], [33, 55, 99])
p2

# Missing Values in an array

Missing Values in an array

In [116]:
a = np.array([10 ,np.nan,20,30,60,np.nan,90,np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [117]:
# Search for missing values and return as a boolean array
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [118]:
a[np.isnan(a)]

array([nan, nan])

In [119]:
# Index of missing values in an array
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

In [121]:
a[np.isnan(a)] =99

In [122]:
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [123]:
# Check if array has any NULL value
np.isnan(a).any()

False

In [124]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Common items between two Arrays

In [147]:
c1 = np.array([10,20,30,40,50,60])
c2 = np.array([12,20,33,40,55,60])

In [126]:
np.intersect1d(c1,c2)

array([20, 40, 60])

# Remove Common Elements

In [131]:
# Remove common elements of C1 & C2 array from C1
np.setdiff1d(c1,c2)

array([10, 30, 50])

In [145]:
np.where(c1 == c2) # returns the indices of elements in an input array where the given condition is satisfied.

(array([], dtype=int64),)

In [138]:
a = np.array([1,2,3,6,8])
b = np.array([10,2,30,60,8])

In [146]:
np.where(c1 == c2) # returns the indices of elements in an input array where the given condition is satisfied.

(array([], dtype=int64),)

In [142]:
c1[np.where(c1 == c2)]


array([20, 40, 60])

In [158]:
 a1=np.random.randint(0,500,10)
 a1

array([304, 231, 358, 446, 183,  97, 436, 315, 236, 305])

In [161]:
a1[np.where((a1>100)&(a1<300))]

array([231, 183, 236])

# Reverse Array

In [162]:
a3 = np.array([[3,2,8,1] , [70,50,10,67] , [45,25,75,15] , [12,9,77,4]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15],
       [12,  9, 77,  4]])

In [163]:
# Reverse ROW positions
a3[::-1,]

array([[12,  9, 77,  4],
       [45, 25, 75, 15],
       [70, 50, 10, 67],
       [ 3,  2,  8,  1]])

In [166]:
# Reverse COLUMN positions
a3[:,::-1]


array([[ 1,  8,  2,  3],
       [67, 10, 50, 70],
       [15, 75, 25, 45],
       [ 4, 77,  9, 12]])

In [170]:
# first 3 rows and 3 column of the matrix
a3[:3,:3,] 

array([[ 3,  2,  8],
       [70, 50, 10],
       [45, 25, 75]])

In [171]:
# Reverse both ROW & COLUMN positions
a3[::-1,::-1]

array([[ 4, 77,  9, 12],
       [15, 75, 25, 45],
       [67, 10, 50, 70],
       [ 1,  8,  2,  3]])

# Sorting Array

In [178]:
a3 = np.array([[3,2,8,1] , [70,50,10,67] , [45,25,75,15]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15]])

In [179]:
# Sort along rows
np.sort(a3)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [180]:
# Sort along rows
np.sort(a3,axis =1)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [181]:
# Sort along columns
np.sort(a3,axis =0)

array([[ 3,  2,  8,  1],
       [45, 25, 10, 15],
       [70, 50, 75, 67]])

In [183]:
# Sort in descending order
b = np.sort(a)
b = b[::-1]
b

array([8, 6, 3, 2, 1])

In [194]:
p = np.arange(0,50)
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [195]:
np.random.shuffle(p)
p

array([18, 17, 31,  1, 46, 33, 20,  3, 35, 12, 14, 27, 36, 45,  6, 48, 10,
        7, 15, 29, 39, 24,  2, 30, 21, 28, 43, 37, 41, 22, 25, 32, 16, 11,
        4,  9, 26, 40,  0, 49, 42, 34, 23, 19, 44,  8, 13, 38, 47,  5])

In [196]:
#p.reshape(5,10)

In [199]:
# Return "n" largest numbers in an Array
n = 4
p[np.argsort(p)[-n:]]

array([46, 47, 48, 49])

In [204]:
p[np.argsort(p)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])