In [1]:
import numpy as np

##Introduction to numpy

In [2]:
a1= np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
a1.dtype

dtype('int32')

In [5]:
a1.size

3

In [6]:
a1.ndim

1

In [7]:
a3=np.array([[[1,2,3],
             [5,6,7],
             [8,6,4]],
             [[2,4,6],
             [3,1,6],
             [4,6,9]]])

In [8]:
a3

array([[[1, 2, 3],
        [5, 6, 7],
        [8, 6, 4]],

       [[2, 4, 6],
        [3, 1, 6],
        [4, 6, 9]]])

In [9]:
a3.ndim

3

In [10]:
a2=np.array([[1,2,3],
     [5,6,7]])

In [11]:
a2

array([[1, 2, 3],
       [5, 6, 7]])

In [12]:
a2.ndim

2

In [13]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [14]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [15]:
import pandas as pd

In [16]:
df = pd.DataFrame(a2)

In [17]:
df

0  1  2
0  1  2  3
1  5  6  7

In [18]:
sample_array=np.ones((2,3))

In [19]:
sample_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
array2= np.ones_like(df,float)

In [21]:
array2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
## For one dimentional random array
array3=np.arange(1,20,3) 

In [23]:
array3

array([ 1,  4,  7, 10, 13, 16, 19])

In [24]:
## For 2 dimentional random array

## First method

array4= np.random.randint(0,10,size=(2,3))
array4


array([[8, 8, 1],
       [3, 4, 6]])

In [25]:
## For 2 dimentional random array

## Second method


array5= np.random.random((2,3))

In [26]:
array5

array([[0.89865395, 0.06702709, 0.55785625],
       [0.56250504, 0.12056858, 0.73546481]])

In [27]:
a3

array([[[1, 2, 3],
        [5, 6, 7],
        [8, 6, 4]],

       [[2, 4, 6],
        [3, 1, 6],
        [4, 6, 9]]])

In [28]:
a3.size

18

In [29]:
a3.ndim

3

In [30]:
a3.shape

(2, 3, 3)

In [31]:
a3[:1,:2,:2]

array([[[1, 2],
        [5, 6]]])

In [32]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 2, 1, 4, 2],
         [7, 4, 4, 8, 4],
         [1, 2, 3, 8, 5],
         [3, 1, 2, 2, 0]],

        [[6, 0, 8, 9, 0],
         [7, 2, 5, 1, 3],
         [4, 9, 8, 6, 1],
         [2, 8, 3, 4, 5]],

        [[7, 7, 1, 0, 8],
         [9, 9, 2, 2, 8],
         [2, 1, 4, 8, 8],
         [3, 5, 4, 2, 7]]],


       [[[3, 0, 0, 4, 1],
         [0, 5, 7, 9, 6],
         [7, 3, 8, 3, 4],
         [1, 7, 5, 0, 3]],

        [[1, 8, 5, 1, 2],
         [8, 3, 6, 3, 9],
         [6, 0, 1, 5, 0],
         [1, 7, 6, 3, 8]],

        [[9, 6, 1, 7, 0],
         [1, 2, 0, 8, 3],
         [3, 4, 5, 8, 5],
         [8, 1, 2, 9, 6]]]])

In [33]:
a4.size,a4.ndim

(120, 4)

In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9])

newarr = arr.reshape(3, 3)

print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[0,-3])


Last element from 2nd dim:  3


In [36]:
arr1=np.arange(2,100,step=4)

In [37]:
arr1

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66,
       70, 74, 78, 82, 86, 90, 94, 98])

In [38]:
arr1[::]

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66,
       70, 74, 78, 82, 86, 90, 94, 98])

In [39]:
arr1[-3:-1]

array([90, 94])

In [40]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],dtype='S')

print(arr.dtype)

print(arr[1, 1:4])

print(arr[0:2, 2])

print(arr[0:2, 1:4])

|S2
[b'7' b'8' b'9']
[b'3' b'8']
[[b'2' b'3' b'4']
 [b'7' b'8' b'9']]


In [41]:

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [42]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [43]:
##Every NumPy array has the attribute base that returns None if the array owns the data.

##Otherwise, the base  attribute refers to the original object.

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)
arr.shape

None
[1 2 3 4 5]


(5,)

In [44]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [45]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

print(arr.base)

arr

[1 2 3 4 5 6 7 8]
None


array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [47]:
arr1= np.array([[6, 7, 1, 5, 9],
         [2, 9, 2, 7, 0],
         [1, 5, 4, 8, 9],
         [3, 9, 5, 7, 0]])

newarr = arr1.reshape(2,2,-1)

print(newarr)

[[[6 7 1 5 9]
  [2 9 2 7 0]]

 [[1 5 4 8 9]
  [3 9 5 7 0]]]


In [48]:
arr1= np.array([[
         [6, 7, 1, 5, 9],
         [2, 9, 2, 7, 0],
         [1, 5, 4, 8, 9],
         [3, 9, 5, 7, 0]],
                
         [[3, 6, 1, 5, 2],
         [6, 0, 1, 9, 4],
         [8, 5, 8, 0, 4],
         [0, 2, 5, 9, 3]]])

for x in arr1:
  for y in x:
    print(y)

    


[6 7 1 5 9]
[2 9 2 7 0]
[1 5 4 8 9]
[3 9 5 7 0]
[3 6 1 5 2]
[6 0 1 9 4]
[8 5 8 0 4]
[0 2 5 9 3]


In [49]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [50]:
arr1= np.array([[
         [6, 7, 1, 5, 9],
         [2, 9, 2, 7, 0],
         [1, 5, 4, 8, 9],
         [3, 9, 5, 7, 0]],
                
         [[3, 6, 1, 5, 2],
         [6, 0, 1, 9, 4],
         [8, 5, 8, 0, 4],
         [0, 2, 5, 9, 3]]])


for x in np.nditer(arr1):
    print(x)

6
7
1
5
9
2
9
2
7
0
1
5
4
8
9
3
9
5
7
0
3
6
1
5
2
6
0
1
9
4
8
5
8
0
4
0
2
5
9
3


In [51]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [52]:
arr2=np.arange(9).reshape(3,3)

arr2

for x in arr2:
    print(x)

[0 1 2]
[3 4 5]
[6 7 8]


In [53]:
for x in np.nditer(arr2, order='C'):
    print (x)


0
1
2
3
4
5
6
7
8


In [54]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [55]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [56]:

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [57]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [58]:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2))

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [59]:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [60]:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [61]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [62]:

arr = np.arange(9).reshape(3,3)

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[[0 1 2]]
[[3 4 5]]
[[6 7 8]]


In [63]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [64]:
arr = np.array([6, 8, 8, 9])

x = np.searchsorted(arr, 11)

print(x)

4


In [65]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]
