In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
%matplotlib inline

In [2]:
data=pd.read_csv("trndata.csv")

In [3]:
data.head()

F1      F2      F3      F4      F5      F6      F7      F8      F9  \
0  0.3315  0.2156  0.6802  0.1434  0.6825  0.2720  0.6223  0.2092  0.7961   
1  0.0939  1.0089  0.0365  0.6944  0.0908  0.4961  0.0722  0.6521 -0.0130   
2  0.5184  0.2283  0.5300  0.6884  0.7456  0.6171  0.6136  0.5928  0.7678   
3  0.4208  0.6740  0.1651  0.7592  0.1810  0.5448  0.1707  0.7554  0.1635   
4  0.3130  0.6465  0.5908  0.6924  0.7664  0.6262  1.7177  0.0150  0.0851   

      F10     F11     F12  L  
0  0.1530  0.5856  0.2573  1  
1  0.6085  0.0631  0.6597  2  
2  0.6130  0.6705  0.5202  1  
3  0.5492  0.2598  0.6455  2  
4  1.9046 -0.0165  0.0221  3

In [4]:
df=data[(data['L']==1)|(data['L']==2)]

In [5]:
df

F1      F2      F3      F4      F5      F6      F7      F8      F9  \
0    0.3315  0.2156  0.6802  0.1434  0.6825  0.2720  0.6223  0.2092  0.7961   
1    0.0939  1.0089  0.0365  0.6944  0.0908  0.4961  0.0722  0.6521 -0.0130   
2    0.5184  0.2283  0.5300  0.6884  0.7456  0.6171  0.6136  0.5928  0.7678   
3    0.4208  0.6740  0.1651  0.7592  0.1810  0.5448  0.1707  0.7554  0.1635   
5    1.1458 -0.0467  0.4056  0.5662  0.3123  0.4580  0.3636  0.6134  0.3305   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
992  0.9463  0.0202  1.3809  0.1522  1.6763  0.0578  1.3851  0.1532  1.6485   
994  0.1724  0.3817  0.1702  0.7203  0.2873  0.7049  0.2921  0.5731  0.3515   
996  0.1263  0.6105  0.2655  0.8748  0.2336  1.0768  0.1833  0.9726  0.3004   
997  0.6043  0.4914  1.0900  0.5961  1.0569  0.8966  1.0279  0.6694  1.2127   
998  1.0284  0.0893  0.4097  0.9375  0.2813  0.6865  0.3827  0.9620  0.2830   

        F10     F11     F12  L  
0    0.1530  0.5856  0.2573  1  
1    0.6085  0.0631  0.6597  2  
2    0.6130  0.6705  0.5202  1  
3    0.5492  0.2598  0.6455  2  
5    0.4132  0.4167  0.5514  2  
..      ...     ...     ... ..  
992  0.1135  1.3393  0.2017  1  
994  0.6442  0.2986  0.5659  1  
996  1.0165  0.1962  0.9532  1  
997  0.7549  1.0654  0.6278  1  
998  0.6586  0.3508  1.0086  2  

[659 rows x 13 columns]

In [6]:
df["L"].replace(2,0,inplace=True)


C:\Python\anaconda3\lib\site-packages\pandas\core\generic.py:6746: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


In [7]:
df.head()

F1      F2      F3      F4      F5      F6      F7      F8      F9  \
0  0.3315  0.2156  0.6802  0.1434  0.6825  0.2720  0.6223  0.2092  0.7961   
1  0.0939  1.0089  0.0365  0.6944  0.0908  0.4961  0.0722  0.6521 -0.0130   
2  0.5184  0.2283  0.5300  0.6884  0.7456  0.6171  0.6136  0.5928  0.7678   
3  0.4208  0.6740  0.1651  0.7592  0.1810  0.5448  0.1707  0.7554  0.1635   
5  1.1458 -0.0467  0.4056  0.5662  0.3123  0.4580  0.3636  0.6134  0.3305   

      F10     F11     F12  L  
0  0.1530  0.5856  0.2573  1  
1  0.6085  0.0631  0.6597  0  
2  0.6130  0.6705  0.5202  1  
3  0.5492  0.2598  0.6455  0  
5  0.4132  0.4167  0.5514  0

In [8]:
df[df['L']==0].head()

F1      F2      F3      F4      F5      F6      F7      F8      F9  \
1   0.0939  1.0089  0.0365  0.6944  0.0908  0.4961  0.0722  0.6521 -0.0130   
3   0.4208  0.6740  0.1651  0.7592  0.1810  0.5448  0.1707  0.7554  0.1635   
5   1.1458 -0.0467  0.4056  0.5662  0.3123  0.4580  0.3636  0.6134  0.3305   
10  1.1308 -0.0286  1.0005  0.7387  0.8390  0.1874  1.0848  0.6374  0.8534   
11  0.5093  0.6038  0.2874  0.8162  0.2267  0.6181  0.2646  0.8490  0.3365   

       F10     F11     F12  L  
1   0.6085  0.0631  0.6597  0  
3   0.5492  0.2598  0.6455  0  
5   0.4132  0.4167  0.5514  0  
10  0.1373  1.0422  0.6836  0  
11  0.4648  0.2815  0.8254  0

In [9]:
df['L'].unique()

array([1, 0], dtype=int64)

In [10]:
x = df.iloc[:,:12]

In [11]:
x.head(3)

F1      F2      F3      F4      F5      F6      F7      F8      F9  \
0  0.3315  0.2156  0.6802  0.1434  0.6825  0.2720  0.6223  0.2092  0.7961   
1  0.0939  1.0089  0.0365  0.6944  0.0908  0.4961  0.0722  0.6521 -0.0130   
2  0.5184  0.2283  0.5300  0.6884  0.7456  0.6171  0.6136  0.5928  0.7678   

      F10     F11     F12  
0  0.1530  0.5856  0.2573  
1  0.6085  0.0631  0.6597  
2  0.6130  0.6705  0.5202

In [12]:
y = df.iloc[:,12:]

In [13]:
y.head(3)

L
0  1
1  0
2  1

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=5)

In [16]:
x_train.shape,y_train.shape

((461, 12), (461, 1))

In [17]:
x_test.shape,y_test.shape

((198, 12), (198, 1))

In [18]:
x_train.describe()

F1          F2          F3          F4          F5          F6  \
count  461.000000  461.000000  461.000000  461.000000  461.000000  461.000000   
mean     0.588423    0.311000    0.545551    0.648077    0.535317    0.604713   
std      0.382832    0.293625    0.336427    0.369489    0.337884    0.355764   
min     -0.042100   -0.178300   -0.066500   -0.125600   -0.078700   -0.102500   
25%      0.277100    0.055200    0.281000    0.365500    0.280900    0.333300   
50%      0.484300    0.283900    0.514800    0.630600    0.492200    0.563500   
75%      1.038400    0.500700    0.740700    0.872100    0.745800    0.842300   
max      1.255500    1.128400    1.839300    1.679500    1.891400    1.734700   

               F7          F8          F9         F10         F11         F12  
count  461.000000  461.000000  461.000000  461.000000  461.000000  461.000000  
mean     0.550027    0.642447    0.541433    0.590129    0.548657    0.644264  
std      0.338509    0.364697    0.344179    0.348466    0.339219    0.371304  
min     -0.052600   -0.056800   -0.069100   -0.107500   -0.093300   -0.059500  
25%      0.277500    0.348900    0.291500    0.327000    0.293600    0.355800  
50%      0.528500    0.633300    0.497700    0.558200    0.520400    0.651100  
75%      0.745700    0.894700    0.769300    0.810100    0.753100    0.885400  
max      1.780600    1.694200    1.882900    1.670000    1.756400    1.713800

In [19]:
y_train.describe()

L
count  461.000000
mean     0.524946
std      0.499920
min      0.000000
25%      0.000000
50%      1.000000
75%      1.000000
max      1.000000

In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
sc=StandardScaler()

In [22]:
x_train_sc=sc.fit_transform(x_train)

In [23]:
x_test_sc=sc.fit_transform(x_test)

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
classifier=LogisticRegression(random_state=4)

In [26]:
classifier.fit(x_train_sc,y_train)

C:\Python\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LogisticRegression(random_state=4)

In [27]:
y_pred=classifier.predict(x_test)

In [28]:
y_pred

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0],
      dtype=int64)

In [29]:
y_test.head()

L
583  0
365  1
271  0
72   1
432  1

In [30]:
from sklearn.metrics import confusion_matrix

In [31]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[97,  0],
       [25, 76]], dtype=int64)

In [32]:
from sklearn.metrics import accuracy_score

In [33]:
print("accuracy score=", accuracy_score(y_test,y_pred))

accuracy score= 0.8737373737373737


In [34]:
classifier.predict(np.arange(12).reshape(-12, 12))

array([1], dtype=int64)

In [35]:
np.arange(10,22).reshape(-12, 12)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]])

In [36]:
plt.plot(x_test_sc,y_pred)

AttributeError: module 'matplotlib' has no attribute 'plot'